### ISSUE TITLE
`Search` after `Put` by OID 

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-testcases#182]
При тестировании глаголов во многих тест-кейсах пут делается с пользовательскими атрибутами, а потом по ним же делается серч. За исключением случаев, когда теструется поиск по фильтрам, в таком подходе нет необходимости -- достаточно получать OID из пута и делает серч по этому OID.

**Comment by roman-khimov** [comment]
If we have an OID no search should be performed at all. @evgeniiz321, do we still have cases like this?

**Comment by evgeniiz321** [comment]
I don't see them in our current tests, we perform search only when we are testing search, I don't see an excessive usage of it.
