### ISSUE TITLE
Test container and object operations with session token

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-testcases#226]
Now we test only Container Put with session token.
[Available operations](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/session/types.proto#L48) for container
[Available operations](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/session/types.proto#L13) for object

**Comment by abereziny** [comment]
We added tests #411 and #445
