### ISSUE TITLE
Correct Complex Object tests with user attributes

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-testcases#232]
@cthulhu-rider 
Исследовал почему проваливается этот тест https://github.com/nspcc-dev/neofs-testcases/blob/master/robot/testsuites/integration/acl/acl_bearer_filter_userheader_equal.robot
Он ожидает, что выдав в bearer токене разрешение на считывание жирного объекта по юзер атрибуту, объект можно будет загетать. В текущей реалии это не так из-за невозможности собрать объект - в мелких кусках атрибутов нет. Это уже обсуждалось здесь https://neospcc.atlassian.net/wiki/spaces/NEOF/pages/2213281813

Предложение по исправлению: для сложного объекта создавать контейнер на одну ноду

**Comment by roman-khimov** [comment]
It all works now and we have some tests for this (#786).
