### ISSUE TITLE
Test presigned URLs in S3 Gateway

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-testcases#241]
After https://github.com/nspcc-dev/neofs-s3-gw/pull/531 S3 Gateway supports presigned URLs. See `docs/authmate.md` to find our how generate such URL.

**Comment by roman-khimov** [comment]
Is it covered by s3-tests? I don't want to duplicate those.

**Comment by roman-khimov** [comment]
@evgeniiz321?

**Comment by evgeniiz321** [comment]
@roman-khimov for some reason there are only negative tests with presigned URLs, need to extend them with a couple positive scenarios
