### ISSUE TITLE
Inner Ring permissions are expected incorrectly

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-testcases#245]
Currently several testcases of basic ACL scenarios fail on
```
${S_OID_SYS_IR} =    Put Object        ${IR_WALLET_PATH}    ${FILE_S}    ${PRIV_CID}    wallet_config=${IR_WALLET_CONFIG}
```
This step tries to store the object using Inner Ring wallet and exits with
```
rpc error: client failure: status: code = 2048 message = access to object operation denied: access to operation OBJECT_PUT is denied by basic ACL check
```

According to NeoFS ACL specification Inner Ring is not allowed to writing operations, so command executes normally.

I propose to make these tests to expect `ACCESS_DENIED` error. 

## Test ENV
* `node@v0.29.0`
* `devenv@88d5342b57ecdd989b461b760db5df349a89b6a0`
* `testcases@7abb2761c92abd0f0d649b17ab9b81d863d05e38`

**Comment by roman-khimov** [comment]
Outdated.
