### ISSUE TITLE
Test run fails against system deployed with morph control roles

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-testcases#269]
After changes made in https://github.com/nspcc-dev/neofs-testcases/pull/267 we cannot run tests against instance of neofs deployed with https://github.com/nspcc-dev/morph-control.

Reason is that wallets created by morph control do not conform to schema expected by [neo3](https://github.com/CityOfZion/neo-mamba)

**Comment by roman-khimov** [comment]
morph-control is gone, likely we can't reproduce it now. Running testcases against some external network is a separate matter.
