### ISSUE TITLE
Calculate address inside the `create_session_token`

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-testcases#303]
Now we pass both wallet and its address into the [create_session_token](https://github.com/nspcc-dev/neofs-testcases/blob/develop/robot/resources/lib/python_keywords/session_token.py#L82) function. These parameters are superflows, as we might calculate the wallet address inside the function. 
One needs to get rid of `address` calculation in the test case because it isn't used anywhere.

**Comment by roman-khimov** [comment]
Some tests may want to have strange tokens, so an additional parameter doesn't hurt.
