### ISSUE TITLE
Could not run tests via instructions in `README.md`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#410]
Some steps that helped me (should be reviewed for sure):

1. removing `submodules` [dep](https://github.com/nspcc-dev/neofs-testcases/blob/a7817304d5f55e9df2a56f14fe7e8a456e0bf3de/venv_template.mk#L4);
2. setting `bash` as a [default shell](https://github.com/nspcc-dev/neofs-testcases/blob/a7817304d5f55e9df2a56f14fe7e8a456e0bf3de/Makefile#L5), `sh` does not have `source`. why has it been changed to `?=`?;
3. removing the [line](https://github.com/nspcc-dev/neofs-testcases/blob/a7817304d5f55e9df2a56f14fe7e8a456e0bf3de/venv_template.mk#L10) (useless now like the `neofs-keywords`?);
4. add `neofs-testlib` and `PyYAML` to the [deps](https://github.com/nspcc-dev/neofs-testcases/blob/master/venv/local-pytest/requirements.txt) and update `requests` lib;
5. `neofs-authmate` binary name is outdated compared to the original repo;
6. `5.` was a required step the same way it required me to install `aws` (do i really need them for `neofs-node` tests? it just prints versions as i understood);
7. fix known `unsupported hash type ripemd160` issue that was not found by me in any instructions.

Optional: it was not so obvious for me to understand that it *not gonna work* with `3.10` python at all

**Comment by carpawell** [comment]
Also, some thoughts:
1. Would be nice to add to some kind of FAQ (not existing yet) info about allure dir rights for a correct report reading.
2. It would be more convenient to run _named_ allure container.

**Comment by aprasolova** [comment]
[This](https://stackoverflow.com/questions/72409563/unsupported-hash-type-ripemd160-with-hashlib-in-python) helped me to fix (7).

**Comment by aprasolova** [comment]
> @aprasolova please, correct me if I am wrong:
> 
>     1. I suppose PR [Remove `neofs-keywords` dependency and fix `make venv.local-pytest` #409](https://github.com/nspcc-dev/neofs-testcases/pull/409) fixes points 1, 2, 3?
> 
>     2. And hopefully we will remove duplicate requirements file in virtual env to address p.4.

You're right in both points. Issue addressed in (4) also fixed in the PR #409.

**Comment by carpawell** [comment]
> [This](https://stackoverflow.com/questions/72409563/unsupported-hash-type-ripemd160-with-hashlib-in-python) helped me to fix (7).

@aprasolova, yeah, me too and that is why i called it a "known issue". Just wanted to mention that it is quite a common problem and could affect some fresh commonly used linux (at least) distros and that is why IMO it deserves mentioning in some kind of FAQ.

**Comment by notimetoname** [comment]
@roman-khimov, yeah, I was quite OK now. BUT I have to admit that the machine I use is the same. Some steps _could_ be still actual for fresh users/machines.

**Comment by roman-khimov** [comment]
OK, I guess there is nothing to fix immediately here then and we'll find out anything new when there will be someone new trying to set it all up.
