### ISSUE TITLE
[NEW TEST] `GETRANGE` with offset == small object boundary

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#466]
### Context

A rare panic [was found](https://github.com/nspcc-dev/neofs-node/issues/2095) and [fixed](https://github.com/nspcc-dev/neofs-node/pull/2101) for the `GETRANGE` operation.

### Testcase

Consider an object cutting:

`[0---------10][11---------20][21---------30]` where numbers represent byte number order in the object payload.

Panic appeared if a client (e.g. `neofs-cli`) requested any range that had an offset that equaled a left small object boundary (e.g. 11). A node responsible for object collecting requested `[21, 10]`, `[11, 10]` *AND* `[10, 0]` ranges. The last one is a parasite request on the one hand but also is a [prohibited](https://github.com/nspcc-dev/neofs-sdk-go/blob/a690dcb159177f3036f9567cda4b30778ec2c0b0/client/object_get.go#L677) one in the SDK client on the other hand. After the fix, `[11, 20]` should work correctly and no nodes must panic.

**Comment by abereziny** [comment]
It seems that we also need to add test to check each object chunk ?

**Comment by carpawell** [comment]
The desired test should call any range request that starts with `0`/`11`/`21` in the provided example. And no nodes must panic.

**Comment by abereziny** [comment]
Added in #477

**Comment by abereziny** [comment]
Passed on v1.0.1-nb-20221223.1 
(Complex object size 5500, maxObjectSize 1500, verified ranges [0-1499],[1500-2999], [3000-4499], [4500,5499])
![image](https://user-images.githubusercontent.com/116558828/209321663-e6b7348a-539e-41b2-937b-2377e59a1137.png)
