### ISSUE TITLE
Adapt changes in `neofs-cli object range`

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#476]
### Context
See [comments](https://github.com/nspcc-dev/neofs-node/pull/2101#discussion_r1039662739) for details.

### Problem
`neofs-cli` does not allow zero length and `uint64` overflow ranges (offset + length <= offset) now. Check that tests are ready for that (add some additional test cases if needed).
Error messsages: `"invalid '%s' range: zero length"`, `"invalid '%s' range: uint64 overflow"` where `%s` is for provided ranges (`off:len`).

**Comment by abereziny** [comment]
Updated in #477

**Comment by abereziny** [comment]
Adapted and passed on v1.0.1-nb-20221223.1
![image](https://user-images.githubusercontent.com/116558828/209323100-4018515e-ba49-40df-b903-c304f6979765.png)
