### ISSUE TITLE
Get rid of NEOFS_ADM_CONFIG_PATH and NEOFS_ADM_EXEC variables

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-testcases#509]
We should be taking path to exec from host.clis list. This way we will be able to get rid of NEOFS_ADM_EXEC parameter completely.

In attributes of the CLIConfig we can store path to config of neofs-adm, this way we can get rid of NEOFS_ADM_CONFIG_PATH variable too.

_Originally posted by @vdomnich-yadro in https://github.com/nspcc-dev/neofs-testcases/pull/500#discussion_r1067801736_

**Comment by EliChin** [comment]
It will be cost-inefficient to implement this change because it will take more time to refactor than it takes for the program to write it from the environment once before testsetup.

**Comment by roman-khimov** [comment]
:wave: Yeah, environment variables are somewhat convenient for this. @vvarg229, @evgeniiz321?
