### ISSUE TITLE
status: code = 1024 message = malformed request: token is invalid at NUMBER epoch

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-testcases#520]
Tests fail with an error:

`AssertionError: Regex pattern 'code = 4097.*message = expired session token' does not match "Command: neofs-cli --config /home/varg/work/neofs-testcases/wallet_config.yml object head --rpc-endpoint 's01.neofs.devenv:8080' --wallet '/home/varg/work/neofs-testcases/TemporaryDir/31074b7b-d8b6-4b34-9555-67c7a443099b.json' --cid 'Ee3UfhzgMLdtAVapPSGzsBiMKtWL3Kzg7ZqwsBK1ubnz' --oid 'EdPd4ffc48eJp4CSGFMXqmAGJR14oYTU2FLLmbahuDMB' --json --session '/home/varg/work/neofs-testcases/TemporaryDir/56efd9ad-8cbd-4ebe-9f6a-d1213feaed57'\nError:\nreturn code: 1\noutput: rpc error: read object header via client: status: code = 1024 message = malformed request: token is invalid at 41 epoch)\n".`

Allure report:
[token_is_invalid.zip](https://github.com/nspcc-dev/neofs-testcases/files/11032529/token_is_invalid.zip)

It looks like a bug in the neofs-node.
But more research is needed to move this issue to the neofs-node project.

**Comment by roman-khimov** [comment]
This, btw, can be fixed in neofs-node master. IIRC there was a number of related changed relatively recently.
