### ISSUE TITLE
Complex object chunk deletion protection lock tests are skipped

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-testcases#535]
The `test_complex_object_chunks_should_also_be_protected_from_deletion` and the `test_link_object_of_complex_object_should_also_be_protected_from_deletion` tests failed with an error at the "Try to delete link object":

```
self = <test_object_lock.TestObjectLockWithGrpc object at 0x7fde1ff78fa0>
locked_storage_object = StorageObjectInfo(cid='4EyFGaKjB7txNPif5Xonb3ustc7q3AD6b2bkqpXoahx4', oid='7TiL3C5a3w9oodHs2QmXE6rSgFQe4ezXuHSEjL5y8L5...KjB7txNPif5Xonb3ustc7q3AD6b2bkqpXoahx4', oid='oSQsZG8T82p7EhCEh5HHunHgvSRutGawDKQesQHkzcM', lifetime=5, expire_at=16)])

    @allure.title("Link object of complex object should also be protected from deletion")
    @pytest.mark.parametrize(
        # Only complex objects are required for this test
        "locked_storage_object",
        [pytest.lazy_fixture("complex_object_size")],
        indirect=True,
    )
    # @pytest.mark.skip(reason='Failed: DID NOT RAISE <class \'Exception\'>')
    def test_link_object_of_complex_object_should_also_be_protected_from_deletion(
        self,
        locked_storage_object: StorageObjectInfo,
    ):
        """
        Link object of complex object should also be protected from deletion
        """
    
        link_object_id = get_link_object(
            locked_storage_object.wallet_file_path,
            locked_storage_object.cid,
            locked_storage_object.oid,
            self.shell,
            self.cluster.storage_nodes,
            is_direct=False,
        )
        with allure.step(f"Try to delete link object {link_object_id}"):
>           with pytest.raises(Exception, match=OBJECT_IS_LOCKED):
E           Failed: DID NOT RAISE <class 'Exception'>

pytest_tests/testsuites/object/test_object_lock.py:669: Failed
```

Allure report: 
[test_object_run.zip](https://github.com/nspcc-dev/neofs-testcases/files/11038285/test_object_run.zip)

**Comment by roman-khimov** [comment]
Please fix the test according to nspcc-dev/neofs-api#253 (see https://github.com/nspcc-dev/neofs-node/issues/2383#issuecomment-1639914640).

**Comment by evgeniiz321** [comment]
Both of these tests suffers from a different problem. There are two assumptions that are checked in these tests:

1. Complex object chunks should also be protected from deletion
2. Link object of complex object should also be protected from deletion

Both of these are currently not true - if we lock a complex object its corresponding chunks are not locked, the same with a link. But we can separately lock each chunk of a complex object, or a link. In this case - they are really locked. But there is no inherit lock from a complex object. 

So the question is - are these assumptions correct? If so - these are product bugs. If no - I will correct tests accordingly.
