### ISSUE TITLE
NeoFS supports homomorphic hashing disabling

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#549]
By @carpawell:

https://github.com/nspcc-dev/neofs-node/pull/1365, v0.30.0

*  It is possible to turn hashing off via the Alphabet in network configuration.
* Containers must be created only with the same setting as set in the network configuration.
* Already created containers must support their original setting despite the current network configuration.

**Comment by cthulhu-rider** [comment]
Tip:

	•	cmd `$ neofs-adm morph set-config -r <endpoint> --alphabet-wallets <dir>`
HomomorphicHashingDisabled=true
	•	check `$ neofs-cli netmap netinfo`
