### ISSUE TITLE
Lock object tests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#550]
By @carpawell:

https://github.com/nspcc-dev/neofs-node/pull/1461, v0.30.0

* It is impossible to delete a locked object (control service is an exception).
* It is impossible to delete a lock object.
* It is prohibited to put a lock object without expiration.
* After lock object expiration, locked objects must become free to delete.

**Comment by vvarg229** [comment]
@roman-khimov @carpawell please explain the concept of "control service":
`It is impossible to delete a locked object (control service is an exception).
`

**Comment by carpawell** [comment]
@vvarg229, in short -- `neofs-cli control`. It allows controlling SN/IR. You should be [authorized](https://github.com/nspcc-dev/neofs-node/blob/27623c50edbb86a09e9b4b368be3e3d399a92969/config/example/node.yaml#L64-L67) to be allowed to make control operations. One of the operations is `neofs-cli control drop-objects`. It means "admin want some object to be removed" and that should be done despite any restriction (e.g. our beloved `LOCK` object).

**Comment by evgeniiz321** [comment]
@roman-khimov could you please take a look at current object lock tests - https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/654-1693496239/index.html#suites/b34feeefa7bd0ee424f598738938f10a/cc81bd598bed3fbb/ ? Looks like all common and useful scenarios are covered

**Comment by roman-khimov** [comment]
@carpawell?

**Comment by carpawell** [comment]
Kinda OK. Mb also add "Lock objects can be dropped"? Not sure what exactly is expected then (should their targets be unlocked?) but still.

Also, some suggestions: I was confused a little by some test naming: some of them have `complex`/`simple` in their title but some of them have that difference as a param; control service testing is mentioned by "drop" word and not by some explicit wording in the title. Also, some CLI commands have double spacing (e.g. `neofs-cli control drop-objects  -o`), which is cosmetic of course.
