### ISSUE TITLE
Fix current dependabot alerts

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#561]
Most of them are irrelevant for the project, but they're irritating anyway: https://github.com/nspcc-dev/neofs-testcases/security/dependabot

**Comment by vvarg229** [comment]
@roman-khimov 
One dependabot warning remains:
https://github.com/nspcc-dev/neofs-testcases/security/dependabot/8 - The [latest version](https://github.com/DiffSK/configobj/releases/tag/v5.0.8) of the configobj is still vulnerable.

What do you think, should I close this issue now or should I wait until the configobj is fixed?

**Comment by vvarg229** [comment]
> separate issue
Done:
https://github.com/nspcc-dev/neofs-testcases/issues/568
