### ISSUE TITLE
Fix dependabot configobj alert

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-testcases#568]
Wait until https://github.com/DiffSK/configobj/issues/232 is fixed and a new release of configobj is released to fix the https://github.com/nspcc-dev/neofs-testcases/security/dependabot/8

**Comment by roman-khimov** [comment]
Likely this unmaintained piece of code can just be replaced, we're using it in one component only.

**Comment by roman-khimov** [comment]
@evgeniiz321, please check if there are any alternatives.
