### ISSUE TITLE
Tests running for 6 hours and failing

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#574]
https://github.com/nspcc-dev/neofs-node/actions/runs/5281297304
> The job running on runner GitHub Actions 4 has exceeded the maximum execution time of 360 minutes.

Needs to be investigated. Maybe it's like #573.

**Comment by vvarg229** [comment]
`The job running on runner GitHub Actions 2 has exceeded the maximum execution time of 360 minutes.
`
From https://github.com/orgs/community/discussions/25700 :
```
Yes, you can change the limit. For GitHub hosted runners, the default value corresponds to the maximum value. You can thus only lower the limit, which you’d do to prevent a runaway job from burning through your free or paid minutes.

For self-hosted runners (which you aren’t using), you can set it to a higher (or lower) value. But you aren’t using them, so this is irrelevant to you.
```

What I plan to do is to remove the "sanity" tests from the full test run. That way we will keep within the limits.

**Comment by roman-khimov** [comment]
But we had tests finish within 1-2 hours just recently, what has changed?

**Comment by vvarg229** [comment]
> But we had tests finish within 1-2 hours just recently, what has changed?

Hmm...
For example, we fixed the S3 tests.
And a lot of other tests.

**Comment by roman-khimov** [comment]
I remember seeing 200+ tests, is that's the count we have now or we're at 500+? I thought this might be an execution-level problem (some test just being stuck), but if that's not the case then it's time for test groups and parallel execution.

**Comment by vvarg229** [comment]
> some test just being stuck

No, we don't have any stuck tests.
You can verify this by checking the timestamps of each test:
[timestamps.txt](https://github.com/nspcc-dev/neofs-testcases/files/11769083/timestamps.txt)

**Comment by vvarg229** [comment]
> I remember seeing 200+ tests

That was before S3 tests were fixed

**Comment by vvarg229** [comment]
S3 tests locally on my laptop are passed successfully:
[s3_gate.zip](https://github.com/nspcc-dev/neofs-testcases/files/11771312/s3_gate.zip)

**Comment by vvarg229** [comment]
And all tests from my laptop:
`================ 16 failed, 249 passed, 33 skipped, 81 warnings in 11334.16s (3:08:54) =================`
Same result and time as from the ubuntu-latest GitHub runners

**Comment by roman-khimov** [comment]
Doesn't seem to be a problem now, `master` tests work fine.
