### ISSUE TITLE
awscli version is not actual

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-testcases#585]
Inside venv by default we have `1.29` version of awscli. But tests should be checked on the v2

**Comment by roman-khimov** [comment]
@evgeniiz321, maybe we should check both? How hard is it to upgrade?

**Comment by vvarg229** [comment]
@smallhive What do you mean by "Inside venv"?
awscli is now manually installed on the host machine:
https://github.com/nspcc-dev/neofs-testcases/blob/master/README.md?plain=1#L52

In CI, we use awscli version 2.13.21 pre-installed on the ubuntu-latest virtual machine from GitHub.

I agree this needs to be changed, but I don't understand why you have an issue with venv?
Can you please execute this commands locally on your laptop and write the output of each command to a comment?

```
make venv.local-pytest
. venv.local-pytest/bin/activate
aws --version
whereis aws
deactivate
aws --version
whereis aws
```

**Comment by smallhive** [comment]
I mean no version inside `requirements.txt`. By default PIP installed v1. Maybe we should put it inside the requirements.

Locally I have already fixed and have v2. The issue is about setting it to the requirements file or mentioning v2 in readme. 
Right now prerequisites looks like:
```
make
python3.10
python3.10-dev
python3.10-venv
libssl-dev
awscli
```
I've just suggestion to update `awscli` -> `awscli v2 (>2.13.0)`. It is only about usability.
