### ISSUE TITLE
GETRANGE and GETRANGEHASH have the same requested length

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#632]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I need to debug RANGE and RANGEHASH requests. A node may produce its own request to satisfy a user's one, and it may be a different request kind (e.g. user's RANGEHASH may produce RANGE). Logs do not allow understanding of what exact request happened cause both RANGE and RANGEHASH have the same length ([here](https://github.com/nspcc-dev/neofs-testcases/blob/7af282f90f32e80301a146c91d9db49ee2bcb0b8/robot/resources/lib/python_keywords/object_access.py#L162) and [here](https://github.com/nspcc-dev/neofs-testcases/blob/7af282f90f32e80301a146c91d9db49ee2bcb0b8/robot/resources/lib/python_keywords/object_access.py#L193)) to the same object usually.

## Describe the solution you'd like
If it does not break other tests, I would like to ask to make ranges different for the different requests (e.g. `[0:9]` and `[0:10]` or even a rand length for a different test suite in the whole test run). They are often run one by one and network communication becomes a mess (a lot of [0:10] RANGE requests).

## Describe alternatives you've considered
Do nothing. I will change those parameters manually every time I run RANGE and RANGEHASH tests then.

## Additional context
Sounds strange but would have saved some time in https://github.com/nspcc-dev/neofs-node/issues/2541 debug.

**Comment by roman-khimov** [comment]
@evgeniiz321, @vvarg229, feasible?

**Comment by vvarg229** [comment]
> @evgeniiz321, @vvarg229, feasible?

It seems feasible.
