### ISSUE TITLE
Do not remove temp files for debug

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#663]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I need to investigate some bug and I have a result (bug), I have a report (some instructions that led to the bug) maybe even a working devenv (if i ran tests locally) but I have no temporary files: tokens, put files, helper files, wallets, etc. So I have a bug, I have a report that says it was a bug, I have logs but I don't have any possibility to reproduce the bug with my own `neofs-cli`, and my own paths to files.

## Describe the solution you'd like
Some ideas:

1. Provide a flag/env/python var/etc that says "DO NOT REMOVE TEMP FILES"
2. Attach temp files related to a failed test to the neofs (if it is a CI run)
3. ...

## Describe alternatives you've considered
Manual Teardown step modifications. Not really a good thing. 

## Additional context
I have not searched for such a flag in this repo so I admit that it may be already implemented but I do not know about it.

**Comment by roman-khimov** [comment]
Option 1 should be easy to do, I'd concentrate on that for now.
