### ISSUE TITLE
Deployment tests with different number of IR nodes

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#694]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when things like https://github.com/nspcc-dev/neofs-node/pull/2695 or https://github.com/nspcc-dev/neofs-node/issues/2681 happen. We're used to using dev-env with its single-node IR, but the system may behave quite differently when we have four or seven nodes.

## Describe the solution you'd like
Test deployments with 1, 4 and 7 nodes.

**Comment by roman-khimov** [comment]
Why is it still open?

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-testcases/pull/801
