### ISSUE TITLE
Separate testing of the NeoFS protocol servers (node cluster) and clients (CLI)

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-testcases#700]
looking at the stuff like #699, with such a vigorous movement to the pure-Python arch, it will be extremely cool to untie cluster testing from the CLI:
- compile the NeoFS protocol client in Python and access the cluster through it (as a result we also get NeoFS Python client SDK)
- test the CLI purely by sniffing its requests and mocking responses

for all tests in group 2 there must be corresponding tests in group 1. In general, group 1 is wider (better protocol coverage, the ability to send fault requests, etc.). CLI will be used by a much smaller target of system users interested in Bucket+Object API mostly. At the same time, we will be able to catch false-positive sending/processing of requests hidden within CLI+cluster pair

---

this can be a huge step in the project. Lets discuss the benefits, overall design of the solution and its implementation plan here. Once the design is ready, suggest to create a group of related tasks

P.S. im not experienced in testing, but willing to help in any way I can

**Comment by roman-khimov** [comment]
Duplicates #258.
