### ISSUE TITLE
Create an s3/gate subscope in the s3 test set

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-testcases#707]
There is a test set for compatibility with `S3 API`. This set has nothing to do with the specifics of the fact that `S3` in `NeoFS` is served through a gate, not directly from the cluster. So if we are testing only `S3 API`, there is no point in writing about the gate. But if we test the `gate` as a standalone application (process) with its custom specifics (for example, reaction to a particular OS signal), then it is worth creating a set of `s3/gate` tests in the `s3` test suite.

> it's a bit strange to me to see `test_s3_gate.py` file in `s3_gate` besides seeing S3 API tests in it. Is this file intended for NeoFS S3 Gateway specifics not covered by the protocol?
> 
> i've left some questions and suggestions from my own, if u'll find any of them useful, feel free to postpone them via issues, i understand that this PR is about migration, not enhancements
> 
> i don't plan to look closely at the other tests (at least for now), hope @evgeniiz321 @roman-khimov will help

_Originally posted by @cthulhu-rider in https://github.com/nspcc-dev/neofs-testcases/pull/699#pullrequestreview-1799554872_

**Comment by roman-khimov** [comment]
I'd suggest creating a subgroup of `s3_extensions` and put neofs-s3-gw-specific tests there. Otherwise it's a standard S3 for bucket/multipart/locking/whatever.
