### ISSUE TITLE
Convert all tests into non-dev-env setup

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#712]
This is an epic to track overall progress of the conversion effort.

* #682
* #683
* #684 
* #685
* #686 
* #687
* #688 
* #689 
* #690 
* #691 
* #692 
* #693 
* #711

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-testcases/pull/734 and https://github.com/nspcc-dev/neofs-node/pull/2765
