### ISSUE TITLE
S3 multipart tests and large object put/get failures 

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-testcases#713]
Currently s3 multipart tests and large object put/get tests are failing, see https://github.com/nspcc-dev/neofs-testcases/pull/708

**Comment by roman-khimov** [comment]
Blocked by https://github.com/nspcc-dev/neofs-node/issues/2447.

**Comment by roman-khimov** [comment]
Should be OK with the current node from master.
