### ISSUE TITLE
Adjust tests to the new token handling behavior

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#718]
We have several session token tests failing after https://github.com/nspcc-dev/neofs-node/pull/2731, the node is fine, tests need to be adjusted.

https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1230-1706624712/index.html#suites/0598eb478b736df2d02c5aa8b49c27f4

**Comment by MaxGelbakhiani** [comment]
While fixing the tests I've discussed with @carpawell if we should get 
`rpc error: status: code = 1024 message = wrong container:` in all current test cases. 

@carpawell noted, that in the case of the session token with
``` "wildcard": true,
      "containerID": null
``` 

There is an issue on the node side.

**Comment by roman-khimov** [comment]
Do we have this issue in neofs-node?

**Comment by MaxGelbakhiani** [comment]
> Do we have this issue in neofs-node?

AFAK, PR from @carpawell is coming

**Comment by MaxGelbakhiani** [comment]
#[2741](https://github.com/nspcc-dev/neofs-node/pull/2741)
