### ISSUE TITLE
Update aiohttp

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#725]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when Dependabot is frustrated. Unfortunately it can't create an update for us in this case.
```
Dependabot can't update vulnerable dependencies without a lockfile
The currently installed version can't be determined.
To resolve the issue add a supported lockfile (Pipfile.lock, pyproject.lock or poetry.lock).
```

## Describe the solution you'd like
1. Update aiohttp to 3.9.2+ (including https://github.com/aio-libs/aiohttp/pull/8074/files)
2. Add lock files for Dependabot.

## Describe alternatives you've considered
Keep getting emails about outdated dependencies, no. Even though the problem itself is not very relevant for us, it's still annoying.

## Additional context
https://github.com/nspcc-dev/neofs-testcases/security/dependabot/19

**Comment by roman-khimov** [comment]
@evgeniiz321, when you create https://github.com/CityOfZion/neo-mamba/pull/304 I expect a link to it here (tracking progress and signaling a dependency) and a `blocked` label.

**Comment by evgeniiz321** [comment]
Dependencies were updated by https://github.com/nspcc-dev/neofs-testcases/pull/760
