### ISSUE TITLE
Do not drop any file if `--persist-env` is provided

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#748]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when i am running tests and have to figure out or guess about what exact key/file/walley/token was used. I hoped that `persist-env` would solved my problem but still scenarios are impossible to repeat locally completely cause TemporaryDir is cleaned even if `--persist-env` is provided.

## Describe the solution you'd like
`--persist-env` does not clean env (wallets are part of the env, whey were used to create containers, some of them are the only ways to get access externally).

## Describe alternatives you've considered
Provide another flag that allows keeping temporary files. But that is likely https://github.com/nspcc-dev/neofs-testcases/issues/663.

**Comment by roman-khimov** [comment]
Duplicates #663 to me, but I'd like to hear @evgeniiz321 opinion.

**Comment by carpawell** [comment]
> Duplicates https://github.com/nspcc-dev/neofs-testcases/issues/663 to me

We did not have --persist-env at that time so not is sounds a little different.
