### ISSUE TITLE
Got `1000:0` range call once 

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#754]
## Current Behavior
I have got this error:
```
RuntimeError: Command: neofs-cli --config /home/carpawell/NSPCC/git/neofs-testcases/wallet_config.yml object hash --rpc-endpoint 'localhost:51385' --wallet '/home/carpawell/NSPCC/git/neofs-testcases/TemporaryDir/1915cfe2-68a5-482e-9358-f3c3775decb2.json' --cid 'GcrhpL4iCTpMC1vNCqjVo6Lnyuhz7RU4jGfNbSiEyb6' --oid 'DJRPtGo7bh5vJ1Z3X8SFqKFx1GV1uhVJqJvMKBy4JWrK' --range '1000:0'
Error:
return code: 1
output: invalid '1000:0' range: zero length
```

in the `tests.object.test_object_api.TestObjectApi#test_object_get_range_hash` and got warning. It does not seems like it should ever be here cause this test is not about invalid ranges.

## Expected Behavior
No zero length in the tests that are about payload (OK tests), not about bounds.

## Possible Solution
Not sure, recheck that zero length is impossible to generate for payload (OK) tests.

## Steps to Reproduce
Just run `tests.object.test_object_api.TestObjectApi#test_object_get_range_hash` test many times (1? 10? 10000000?).

## Context
Saw this once per some runs.

## Your Environment
`df8970940e1128b063c81abf1870f8616e7ce624`

**Comment by carpawell** [comment]
![image](https://github.com/nspcc-dev/neofs-testcases/assets/24619368/6daf7d9d-0144-4289-bbe1-cb3b77ac98a3)

**Comment by roman-khimov** [comment]
Same test, but a different problem: https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/382-1715098385/index.html#suites/87d8da5f92824d091055170c29079bc0/a83d5a688fd68c3b/
