### ISSUE TITLE
`RANGE` tests forgives critical errors

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#758]
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1438-1711140652/index.html#suites/87d8da5f92824d091055170c29079bc0/225827e59eb4b5fe/ has object tests OK but tests about session tokens for RANGE request were sick. Investigation of the problem led to https://github.com/nspcc-dev/neofs-node/pull/2784 fixes. They are quite critical but RANGE tests were OK without them.

## Current Behavior
Ranging over more than one child object is not tested by RANGE tests (at least that is not fixed in the tests).

## Expected Behavior
RANGE tests should test everything possible about complex objects.

## Possible Solution
Test every possible situation about range and child split overflow variations.

## Steps to Reproduce
Run tests for `ff2336912f657825eba9444d22241fbb420013e9` node revision. It is buggy, but most likely RANGE tests will be OK.

**Comment by roman-khimov** [comment]
> RANGE tests should test everything possible about complex objects.

Define "everything possible", please.

**Comment by carpawell** [comment]
> Define "everything possible", please.

At least:

1. range is inside one child
2. range matches child
3. range requires more than one child (it includes OR does not include the first and the last children)
4. range requires more than two children (it includes OR does not include the first and the last children)
5. range overflows object
