### ISSUE TITLE
Add pprof endpoints to the `env_details` for SN and IR applications

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-testcases#767]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see `Pprof address:` for the REST GW and do not see it for other apps. SN and IR are the same apps and they also may be wanted to be pprofed.

## Describe the solution you'd like
Do smth like already done for [REST](https://github.com/nspcc-dev/neofs-testlib/blob/bd41c3752297f6da444a3c0216fb67be33ff8044/src/neofs_testlib/env/env.py#L843).

**Comment by carpawell** [comment]
BTW, REST seems like the only app with pprof in this file, so S3 can be pprofed too, I just do not use it.

**Comment by carpawell** [comment]
`6e96105b8bb4543f6e7685b202d0dc3453432f76` was used.

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-testcases/pull/849
