### ISSUE TITLE
Update S3 tests wrt 0.30.0 release

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#771]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when tests are not up to date with the gateway changes. We have https://github.com/nspcc-dev/neofs-s3-gw/releases/tag/v0.30.0 with a lot of fixes, but tests are still expecting some older behavior.

## Describe the solution you'd like
Check/update tests.

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-testcases/pull/772
