### ISSUE TITLE
Properly test REST gw streaming

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#799]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't have proper tests for some functions. #798 changed `upload_via_http_gate_curl` to not use pipe (we need it for MacOS) and streaming test now uses Python library to upload. Most likely it's not an equivalent replacement since file size is known in this case and it will be passed in meta, also chunked encoding is the thing we want to have for this test.

## Describe the solution you'd like
Arrange proper chunked unknown-size stream test using Python library.

**Comment by evgeniiz321** [comment]
Fixed by https://github.com/nspcc-dev/neofs-testcases/pull/810
