### ISSUE TITLE
RuntimeError: Invalid xk6 directory

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#835]
## Current Behavior
 test_custom_load ends with "RuntimeError: Invalid xk6 directory".
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1813-1723489581/index.html#suites/518ad631d5bce9364944ff5e59e558a7/ebf46726b26bccea/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1813-1723490690/index.html#suites/518ad631d5bce9364944ff5e59e558a7/4db97571e502cb54/

## Expected Behavior
Green.

## Possible Solution
Fix the damn thing.

## Steps to Reproduce
Run neofs-testcases for the current neofs-node master.

## Regression
Very likely, but can't point immediately to where it broke.

**Comment by evgeniiz321** [comment]
Fixed by https://github.com/nspcc-dev/neofs-node/pull/2919
