### ISSUE TITLE
Adapt tests to EACL changes in S3

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#837]
See https://github.com/nspcc-dev/neofs-s3-gw/pull/976, we have different outputs in some cases now.

**Comment by evgeniiz321** [comment]
Only s3 tests were affected by these changes - current s3 gw tests in this repo don't have specific assertions for the updated behavior. Such validations are done only in s3 tests repo. All affected s3 tests are handled by https://github.com/nspcc-dev/s3-tests/issues/72 and https://github.com/nspcc-dev/s3-tests/issues/75
