### ISSUE TITLE
PUT/GET with unavailable node

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#911]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't have any tests for degraded cluster.

## Describe the solution you'd like
4 nodes, REP 3. PUT some objects, take one node down. GET objects. PUT objects. It all should work.

Variations are welcome.

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-testcases/pull/912
